### PR TITLE
Improve on #9

### PR DESCRIPTION
**Pull request by Genki-S**
- Move test files under `test/lib/` to `test/`: https://github.com/Genki-S/ttnt/commit/654181c0c4c406f4fbfcf8fe725ef02496460bc8
- Use `before_setup` and `after_teardown` in MiniTest extension class to avoid calling `super` in setup/teardown in every class extending it: https://github.com/Genki-S/ttnt/commit/82210e776ef7d54a767291a6ac6e125f2db95afc

### CODE REVIEW

**Comment by robin850** [comment]
Great!

**Comment by Genki-S** [comment]
Oops, sorry for submitting order dependent pull requests... Thank you for the fix!
I think 2 pull requests introduced same test file (`test/lib/task_helper_test.rb` and `test/tasks_test.rb`) which are testing the same thing. So I removed one here: https://github.com/Genki-S/ttnt/commit/a3e0f32bd0b7a9764e4996e5b3424c82f7a04620

Working with multiple pull requests is somewhat difficult in this early stage of development, I will be more careful and might create bigger pull request, including some feature at the same time :(

**Comment by robin850** [comment]
Hey, there's no problem at all! This is not something that will often happen ; just a very specific case since you are still setting up the project but you are not going to rename files each time. Keep the current workflow if it's easier for you ; it's ok on my side! :smiley:

**Comment by Genki-S** [comment]
That's very kind of you! I will try out some approaches and see how it goes, then. Thank you very much for being so understanding :wink:

**Pull request merged**
