### PR TITLE
Run selected tests using an instance of `Rake::TestTask`

### PR DESCRIPTION
**Pull request by Genki-S**
As mentioned in #1, I introduced these changes:

- Store the instance of `Rake::TestTask` and use attributes from it (and stop copying instance variables to self): https://github.com/Genki-S/ttnt/commit/c7c2c37d7912042167bd07267a2e4e30c014aa5b
- Run selected tests using methods in `Rake::TestTask`: https://github.com/Genki-S/ttnt/commit/3f232786a4e73c35d459b6a588a58e2bd53facc5

Additionally (since it is somewhat related), I made `ttnt:test:anchor` task regard ruby options specified for `Rake::TestTask` like this: https://github.com/Genki-S/ttnt/commit/ccf67f5089de8b3fb6a4c798ea05f4829ea70d3d

@robin850 could you review the code please?

### CODE REVIEW

**Comment by robin850** [comment]
It looks good to me! :+1:

I would simply rename `rake_testtask` to `test_task` first because we don't mind that it comes from Rake and also in the future we may accept things like `RSpec::TestTask`. What do you think ?

**Comment by Genki-S** [comment]
> I would simply rename rake_testtask to test_task first because we don't mind that it comes from Rake and also in the future we may accept things like RSpec::TestTask

I agree if I can be confident that I can use `Rake::TestTask` and `RSpec::TestTask` (actually it seems `RSpec::Core::RakeTask` is the one which is equivalent) in the same way. We might need to prepare additional wrapper if both are different enough. So, to emphasize it's an instance of `Rake::TestTask` and not of RSpec related instance (yet), I want to keep it named like this (though it's a little too verbose :sweat_drops: ). I would like to rename it when I support RSpec :smile:

**Comment by robin850** [comment]
> We might need to prepare additional wrapper if both are different enough

Yep, we will end up manipulating a task-like object but anyway, if you want to keep it as is for now and change later, then you can merge this. :+1:

**Comment by Genki-S** [comment]
Thank you! :smile:

**Pull request merged**
